// Official DoD Federal Supply Groups (78 two-digit codes)
export const FSC_GROUPS: Record<string, string> = {
  '10': 'Weapons',
  '11': 'Nuclear Ordnance',
  '12': 'Fire Control Equipment',
  '13': 'Ammunition & Explosives',
  '14': 'Guided Missiles',
  '15': 'Aircraft & Airframe Structural Components',
  '16': 'Aircraft Components & Accessories',
  '17': 'Aircraft Launching, Landing & Ground Handling Equipment',
  '18': 'Space Vehicles',
  '19': 'Ships, Small Craft, Pontoons & Floating Docks',
  '20': 'Ship & Marine Equipment',
  '22': 'Railway Equipment',
  '23': 'Ground Effect Vehicles, Motor Vehicles, Trailers & Cycles',
  '24': 'Tractors',
  '25': 'Vehicular Equipment Components',
  '26': 'Tires & Tubes',
  '28': 'Engines, Turbines & Components',
  '29': 'Engine Accessories',
  '30': 'Mechanical Power Transmission Equipment',
  '31': 'Bearings',
  '32': 'Woodworking Machinery & Equipment',
  '34': 'Metalworking Machinery',
  '35': 'Service & Trade Equipment',
  '36': 'Special Industry Machinery',
  '37': 'Agricultural Machinery & Equipment',
  '38': 'Construction, Mining, Excavating & Highway Maintenance Equipment',
  '39': 'Materials Handling Equipment',
  '40': 'Rope, Cable, Chain & Fittings',
  '41': 'Refrigeration, Air Conditioning & Air Circulating Equipment',
  '42': 'Fire Fighting, Rescue & Safety Equipment',
  '43': 'Pumps & Compressors',
  '44': 'Furnace, Steam Plant & Drying Equipment',
  '45': 'Plumbing, Heating & Sanitation Equipment',
  '46': 'Water Purification & Sewage Treatment Equipment',
  '47': 'Pipe, Tubing, Hose & Fittings',
  '48': 'Valves',
  '49': 'Maintenance & Repair Shop Equipment',
  '51': 'Hand Tools',
  '52': 'Measuring Tools',
  '53': 'Hardware & Abrasives',
  '54': 'Prefabricated Structures & Scaffolding',
  '55': 'Lumber, Millwork, Plywood & Veneer',
  '56': 'Construction & Building Materials',
  '58': 'Communication, Detection & Coherent Radiation Equipment',
  '59': 'Electrical & Electronic Equipment Components',
  '60': 'Fiber Optics Materials, Components & Assemblies',
  '61': 'Electric Wire, Power & Distribution Equipment',
  '62': 'Lighting Equipment & Lamps',
  '63': 'Alarm, Signal & Security Detection Systems',
  '65': 'Medical, Dental & Veterinary Equipment & Supplies',
  '66': 'Instruments & Laboratory Equipment',
  '67': 'Photographic Equipment',
  '68': 'Chemicals & Chemical Products',
  '69': 'Training Aids & Devices',
  '70': 'General Purpose ADP Equipment, Software & Support',
  '71': 'Furniture',
  '72': 'Household & Commercial Furnishings & Appliances',
  '73': 'Food Preparation & Serving Equipment',
  '74': 'Office Machines & Text Processing Systems',
  '75': 'Office Supplies & Devices',
  '76': 'Books, Maps & Other Publications',
  '77': 'Musical Instruments, Phonographs & Home-Type Radios',
  '78': 'Recreational & Athletic Equipment',
  '79': 'Cleaning Equipment & Supplies',
  '80': 'Brushes, Paints, Sealers & Adhesives',
  '81': 'Containers, Packaging & Packing Supplies',
  '83': 'Textiles, Leather, Furs, Apparel & Shoe Findings',
  '84': 'Clothing, Individual Equipment & Insignia',
  '85': 'Toiletries',
  '87': 'Agricultural Supplies',
  '88': 'Live Animals',
  '89': 'Subsistence',
  '91': 'Fuels, Lubricants, Oils & Waxes',
  '93': 'Nonmetallic Fabricated Materials',
  '94': 'Nonmetallic Crude Materials',
  '95': 'Metal Bars, Sheets & Shapes',
  '96': 'Ores, Minerals & Their Primary Products',
  '99': 'Miscellaneous',
}

export function fscLabel(fsc: string): string {
  const group = FSC_GROUPS[fsc.slice(0, 2)]
  return group !== undefined ? `${fsc} — ${group}` : fsc
}
